# -*- coding: utf-8 -*-
"""OCR_para_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZwXAiRmZWHRl6LiFJf3vHQtyXccGBpF
"""

import streamlit as st
import requests
from PIL import Image
import io

st.set_page_config(page_title="OCR com API", layout="centered")
st.title("🖼️ OCR JPEG usando API (OCR.Space)")

API_KEY = "K88173315088957"  # Substitua por sua chave pessoal para uso real

uploaded_file = st.file_uploader("Upload de Arquivos", type=["jpeg", "jpg", "png"])

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image, caption='Imagem carregada', use_container_width=True)

    # Converter imagem para bytes
    img_bytes = io.BytesIO()
    image.save(img_bytes, format="JPEG")
    img_bytes.seek(0)

    with st.spinner("🔍 Realizando OCR na imagem..."):
        response = requests.post(
            "https://api.ocr.space/parse/image",
            files={"filename": img_bytes},
            data={"apikey": API_KEY, "language": "por"},
        )

    result = response.json()

    if result.get("IsErroredOnProcessing"):
        st.error("Erro ao processar imagem. Verifique a chave ou tente outra imagem.")
    else:
        parsed_text = result["ParsedResults"][0]["ParsedText"]
        st.subheader("📑 Texto Detectado:")
        st.code(parsed_text.strip() or "Nenhum texto detectado.")

        # Simulação simples da "porcentagem de leitura"
        palavras = parsed_text.strip().split()
        percentual = min(100, len(palavras) * 5)  # Simples estimativa baseada em nº de palavras
        st.subheader("📊 Porcentagem Estimada de Leitura")
        st.progress(percentual / 100)
        st.write(f"Leitura estimada: **{percentual:.2f}%**")
