# -*- coding: utf-8 -*-
"""OCR_para_streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZwXAiRmZWHRl6LiFJf3vHQtyXccGBpF
"""

import streamlit as st
from PIL import Image
import pytesseract
import numpy as np
import io

st.set_page_config(page_title="OCR com JPEG", layout="centered")

st.title("🖼️ OCR com Imagens JPEG")
st.write("Faça o upload de uma imagem `.jpeg` para realizar a leitura de texto (OCR).")

uploaded_file = st.file_uploader("Upload de Arquivos", type=["jpeg", "jpg"])

if uploaded_file:
    # Mostrar imagem
    image = Image.open(uploaded_file)
    st.image(image, caption='Imagem carregada', use_column_width=True)

    # Realiza OCR
    st.subheader("📑 Texto Detectado (OCR)")
    text = pytesseract.image_to_string(image, lang='por')
    st.code(text if text.strip() else "Nenhum texto detectado.")

    # Estimar porcentagem de leitura
    st.subheader("📊 Porcentagem de Leitura")

    # Cria máscara da imagem com as caixas detectadas
    data = pytesseract.image_to_data(image, lang='por', output_type=pytesseract.Output.DICT)

    total_boxes = len(data['text'])
    text_boxes = sum(1 for word in data['text'] if word.strip() != '')

    if total_boxes > 0:
        percent = (text_boxes / total_boxes) * 100
    else:
        percent = 0.0

    st.progress(percent / 100)
    st.write(f"Percentual estimado de leitura: **{percent:.2f}%**")